version: "3.8"
services:
  db:
    container_name: db-server
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: proj1
      MYSQL_USER: spring_user
      MYSQL_PASSWORD: MySQL123
      MYSQL_ROOT_PASSWORD: MySQL123
    ports:
      - "3307:3306"